# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp core model functions for variable precision models
#'
#' @param x A numeric vector of kappa/J values
#' @param pars A numeric vector of parameter values: RN- c(setsize precision,tau); RN+ c(setsize precision,tau,kappa_r)
#' @param radian A double for error in radian
#' @export
NULL

cint_fun_J_RNminus <- function(x, pars, radian) {
    .Call(`_vwmvp_cint_fun_J_RNminus`, x, pars, radian)
}

cint_fun_J_RNplus <- function(x, pars, radian) {
    .Call(`_vwmvp_cint_fun_J_RNplus`, x, pars, radian)
}

cint_fun_MK_RNminus <- function(x, pars, radian) {
    .Call(`_vwmvp_cint_fun_MK_RNminus`, x, pars, radian)
}

cint_fun_MK_RNplus <- function(x, pars, radian) {
    .Call(`_vwmvp_cint_fun_MK_RNplus`, x, pars, radian)
}

csim_fun_J_RNminus <- function(x, pars, baseradians) {
    .Call(`_vwmvp_csim_fun_J_RNminus`, x, pars, baseradians)
}

csim_fun_J_RNplus <- function(x, pars, baseradians) {
    .Call(`_vwmvp_csim_fun_J_RNplus`, x, pars, baseradians)
}

csim_fun_MK_RNminus <- function(x, pars, baseradians) {
    .Call(`_vwmvp_csim_fun_MK_RNminus`, x, pars, baseradians)
}

csim_fun_MK_RNplus <- function(x, pars, baseradians) {
    .Call(`_vwmvp_csim_fun_MK_RNplus`, x, pars, baseradians)
}

